FROM tomcat:8.5

RUN wget https://github.com/leon7891/rss/releases/download/0.0.1/RSSFeedAggregatorServer.war
RUN cp RSSFeedAggregatorServer.war /usr/local/tomcat/webapps/rss.war

CMD ["catalina.sh", "run"]
